version: "3.9"
services:
  frontend:
    working_dir: /mnt
    command: >
        sh -c "npm install 
        && npm run build
        && npm run start"
    volumes:
      - .:/mnt
    image: deployment-image