name: 'Webpage Screenshot Frontend'
on:
  push:
    tags:
      - v*
jobs:
  frontend:
    name: 'Build Frontend and push to s3'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_REPO_TOKEN }}

      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Build frontend'
        run: npm run build

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.9.8'

      - name: 'Terraform Init'
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Re-import resources with legacy state attributes'
        run: |
          terraform state rm 'module.cloudfrontEdge-s3-module.aws_cloudfront_distribution.cloudfront_distribution' || true
          terraform import 'module.cloudfrontEdge-s3-module.aws_cloudfront_distribution.cloudfront_distribution' ED53IMNBFJBIS
          terraform state rm 'module.cloudfrontEdge-s3-module.aws_route53_record.route53_record[0]' || true
          terraform import 'module.cloudfrontEdge-s3-module.aws_route53_record.route53_record[0]' Z3EVN4UEER4WI3_pagemelt.alexandermorton.co.uk_A
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Sync assets to S3'
        run: |
          aws s3 sync ./dist s3://s3-bucket-shot-frontend --cache-control 'max-age=31536000' --exclude "*.html" --region us-east-1
          aws s3 sync ./dist s3://s3-bucket-shot-frontend --cache-control 'no-cache' --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Invalidate CloudFront cache'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.WEBPAGE_SITE_CF_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
