name: 'Webpage Screenshot Frontend'
on:
  push:
    tags:
      - v*
jobs:
  frontend:
    name: 'Build Frontend and push to s3'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Build frontend'
        run: npm run build

      - name: 'Sync assets to S3'
        run: |
          aws s3 sync ./dist s3://s3-bucket-shot-frontend --cache-control 'max-age=31536000' --exclude "*.html" --region us-east-1
          aws s3 sync ./dist s3://s3-bucket-shot-frontend --cache-control 'no-cache' --region us-east-1

      - name: 'Invalidate CloudFront cache'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.WEBPAGE_SITE_CF_ID }} --paths "/*"
